### ISSUE TITLE
カメラの調査

### ISSUE THREAD

**Issue by RikuUchida** [CIT-Autonomous-Robot-Lab/Tsudanuma_Tsukuba_Challenge_Plan#13]

**Comment by RikuUchida** [comment]
現状：RealSence d435

**Comment by RikuUchida** [comment]
RealSence d435 の仕様
https://www.intelrealsense.com/depth-camera-d435/
Depth

> FOV: 87 * 58
> output resolutin: up to 1280 * 720
> min depth destance: ~28 cm
> FPS: up to 90 fps

RGB

> FOV: 69 * 42
> frame: 1920 * 1080
> FPS: 30 fps

**Comment by uhobeike** [comment]
折り返し雑音

**Comment by uhobeike** [comment]
良いサイトを見つけた
https://www.tegakari.net/2020/09/3dcamera_compare_2/

**Comment by uhobeike** [comment]
zed vs realsenceだと
realsenceが良さそう。

**Comment by uhobeike** [comment]
realsenceD455が良さそう。
https://www.youtube.com/watch?v=RtqfdCUIUrM

**Comment by uhobeike** [comment]
買っとく？

**Comment by uhobeike** [comment]
上田研にあるか聞いてみる。

**Comment by uhobeike** [comment]
@RikuUchida 上田研にあるか聞いてみて。
